# Generated by Django 5.0.4 on 2024-05-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_categorytype_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='types',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Null description'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('ANN', 'Announcements and News'), ('SUP', 'Support and Help'), ('GEN', 'General Discussions'), ('THE', 'Thematic Topics'), ('INT', 'Introductions and Welcomes'), ('NTP', 'No category type')], default='NTP', max_length=3),
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
    ]
