# Generated by Django 5.0.4 on 2024-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0004_rename_type_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_types',
            field=models.ManyToManyField(to='categorys.categorytype'),
        ),
    ]
