# Generated by Django 5.0.4 on 2024-06-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_from_me', to=settings.AUTH_USER_MODEL)),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_to_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
