# Generated by Django 5.0.4 on 2024-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userownmodel',
            name='int_friends',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
