# Generated by Django 5.0.4 on 2024-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userownmodel',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='userownmodel',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
