# Generated by Django 5.0.4 on 2024-09-10 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userownmodel_int_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userownmodel',
            name='followers',
            field=models.ManyToManyField(related_name='rn_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userownmodel',
            name='follows',
            field=models.ManyToManyField(related_name='rn_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userownmodel',
            name='friends',
            field=models.ManyToManyField(related_name='rn_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
