# Generated by Django 5.0.4 on 2024-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='url',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='messagegroup',
            old_name='url',
            new_name='audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='is_audio',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='is_video',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='video',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
